// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD-l8KpG7Goj5liTja4npyt8zuHrlLEmY',
    appId: '1:942870063102:web:c088cc973e9299848202af',
    messagingSenderId: '942870063102',
    projectId: 'pointingpoker-365815',
    authDomain: 'pointingpoker-365815.firebaseapp.com',
    storageBucket: 'pointingpoker-365815.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6brdJJaJZCP1-2qV7Hx5AdJ0dU5h4-ds',
    appId: '1:942870063102:android:606cb275bafeea828202af',
    messagingSenderId: '942870063102',
    projectId: 'pointingpoker-365815',
    storageBucket: 'pointingpoker-365815.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoTPYwt0jxfMiW7qSUzWHu8jIHlBH2oY8',
    appId: '1:942870063102:ios:ce4517d2893474b48202af',
    messagingSenderId: '942870063102',
    projectId: 'pointingpoker-365815',
    storageBucket: 'pointingpoker-365815.appspot.com',
    iosClientId: '942870063102-mavihetie5r7t5qoo6nfgp70c8sfib85.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoTPYwt0jxfMiW7qSUzWHu8jIHlBH2oY8',
    appId: '1:942870063102:ios:ce4517d2893474b48202af',
    messagingSenderId: '942870063102',
    projectId: 'pointingpoker-365815',
    storageBucket: 'pointingpoker-365815.appspot.com',
    iosClientId: '942870063102-mavihetie5r7t5qoo6nfgp70c8sfib85.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
